<a href="https://colab.research.google.com/github/Leshan21/machine-learning/blob/main/learn_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# create array and check array type:


In [4]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# create random arrays using numpy

In [12]:
np.arange(0,10,2) #np.arrange(start point,end point,gap between two numbers)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)  #create zeros array

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,5)) # create multi-diamentional array np.zeros((enter the diamention))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])